In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [15]:
# Get Dimension
b.ndim

2

In [10]:
# Get shape
b.shape

(2, 3)

In [11]:
# Get type
b.dtype

dtype('float64')

In [12]:
# Get size
a.itemsize

4

In [16]:
# Get total size
a.nbytes

12

In [22]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
# Get a specific element[r,c]
a[1, 5]

13

In [24]:
 a[1,-1]

14

In [25]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
a[0,0]

1

In [29]:
a[0,0] = 2
print(a)

[[ 2  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [31]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [32]:
#[startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [36]:
a[0,1:-1:2]

array([2, 4, 6])

In [38]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [39]:
# Get a specific element
b[0,1,1]

4

In [41]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [43]:
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [44]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [46]:
# All 1s matrix
np.ones((4,2,2), dtype='float')

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [47]:
# Anyother
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [48]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [49]:
# Ramdom decimal numbers
np.random.rand(4,2)

array([[0.81042467, 0.14566448],
       [0.03669056, 0.442828  ],
       [0.56005684, 0.4432119 ],
       [0.02374341, 0.66652075]])

In [53]:
# Random Integer values
np.random.randint(4,7, size=(3,3))

array([[4, 6, 5],
       [5, 6, 4],
       [6, 5, 6]])

In [54]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
# Repeat an array
arr  = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [59]:
output = np.ones((5,5))

In [60]:
z = np.zeros((3,3))

In [62]:
z[1,1] = 9
output[1:4,1:4] = z

In [63]:
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [64]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [65]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)


1.0

In [66]:
# Statistics
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
np.min(stats,axis=0)

array([1, 2, 3])

In [68]:
np.max(stats)

6

In [69]:
np.sum(stats)

21

In [70]:
np.sum(stats, axis = 0)

array([5, 7, 9])

In [71]:
np.sum(stats, axis = 1)

array([ 6, 15])

In [72]:
# reorganizing Arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [74]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:

# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])